blog/urls.py
from django.conf.urls import url
from blog import views
urlpatterns = [

    url(r'^upload', views.upload),
    url(r'^delArticle/(?P<article_id>\d+)', views.delArticle),
    url(r'^addArticle', views.addArticle),
    url(r'^comment_up_down', views.comment_up_down),
    url(r'^article_comment', views.article_comment),
    url(r'^article_up', views.article_up),
    url(r'^comment_tree/(?P<article_id>\d+)', views.comment_tree),
    url(r'^tag', views.tag),
    url(r'^category', views.category),
    url(r'^manage', views.manage),
    url(r'^(?P<username>.*)/article/(?P<article_id>.*)', views.article_detail),
    url(r'^(?P<username>.*)/(?P<field>(tag|category|date))/(?P<field_name>.*)', views.homesite),
    url(r'^(?P<username>.*)', views.homesite),



   ]

blogpro/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from blog import views

# 滑动验证码插件
from blog.views import pcgetcaptcha,pcajax_validate

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login),
    url(r'^logout/$', views.logout),
    url(r'^register/$', views.register),
    url(r'^$', views.index),
    url(r'^get_valid_code/$', views.get_valid_code),
    url(r'^cate/(?P<article_cate_name>.*$)', views.index),

    #url分发
    url(r'^blog/', include('blog.urls')),
    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    # 滑动验证码插件

    url(r'^pc-geetest/register', pcgetcaptcha, name='pcgetcaptcha'),

    url(r'^pc-geetest/ajax_validate', pcajax_validate, name='pcajax_validate'),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):  # settings:   AUTH_USER_MODEL = "blog.UserInfo"
    """
    用户信息
    """
    nid = models.BigAutoField(primary_key=True)
    nickname = models.CharField(verbose_name='昵称', max_length=32)
    telephone = models.CharField(max_length=11, blank=True, null=True, unique=True, verbose_name='手机号码')
    avatar = models.FileField(verbose_name='头像', upload_to='avatar', default="/avatar/default.png")
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    站点信息
    """
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题', max_length=64)
    site = models.CharField(verbose_name='个人博客后缀', max_length=32, unique=True)
    theme = models.CharField(verbose_name='博客主题', max_length=32)

    user = models.OneToOneField(to='UserInfo', to_field='nid')

    def __str__(self):
        return self.title


class Category(models.Model):
    """
    博主个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'category'
        ordering = ['title']


class Article(models.Model):
    nid = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name='文章标题')
    desc = models.CharField(max_length=255, verbose_name='文章描述')
    read_count = models.IntegerField(default=0)
    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    siteArticleCategory=models.ForeignKey(verbose_name="站点文章类型",to="SiteArticleCategory",null=True)
    category = models.ForeignKey(verbose_name='文章类型', to='Category', to_field='nid', null=True)
    user = models.ForeignKey(verbose_name='所属用户', to='UserInfo', to_field='nid')
    tags = models.ManyToManyField(
        to="Tag",
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title


class ArticleDetail(models.Model):
    """
    文章详细表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField(verbose_name='文章内容', )

    article = models.OneToOneField(verbose_name='所属文章', to='Article', to_field='nid')

    def __str__(self):
        return self.article.title

class Comment(models.Model):
    """
    评论表
    """
    nid = models.BigAutoField(primary_key=True)

    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid')
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid')

    parent_comment = models.ForeignKey('self', blank=True, null=True, verbose_name='父级评论')

    def __str__(self):
        return self.content


class CommentUp(models.Model):
    """
    评论支持/反对表
    """

    nid = models.AutoField(primary_key=True)
    updown = models.CharField(verbose_name="反对还是支持", max_length=16)
    user = models.ForeignKey('UserInfo', null=True)
    comment = models.ForeignKey("Comment", null=True)

    class Meta:
        unique_together = [
            ('comment', 'user'),
        ]


class ArticleUp(models.Model):
    """
    文章支持/反对表
    """
    nid = models.AutoField(primary_key=True)
    updown=models.CharField(verbose_name="反对还是支持",max_length=16)
    user = models.ForeignKey('UserInfo', null=True)
    article = models.ForeignKey("Article", null=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]


class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid')

    def __str__(self):
        return self.title


class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to="Article", to_field='nid')
    tag = models.ForeignKey(verbose_name='标签', to="Tag", to_field='nid')

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

class SiteCategory(models.Model):
    '''主分类表'''
    name=models.CharField(verbose_name="主分类名",max_length=32)
    def __str__(self):
        return self.name

class SiteArticleCategory(models.Model):
    '''站点文章分类表'''
    name=models.CharField(verbose_name="文章分类名",max_length=32)
    siteCategory=models.ForeignKey(to="SiteCategory")

    def __str__(self):
        return self.name

templates/ArticleDone.html
{% extends "manage.html" %}

{% block content %}

    <div style="background-color: whitesmoke">
    <div style="color: #333333;background: #EEEEEE;border: 1px dashed #CCCCCC;padding: 12px;
font-weight: bold;height: 50px">发布成功</div>
    <p>文章标题：<a href="/blog/{{ request.user.username }}/article/{{ article_obj.nid }}">{{ article_obj.title }}</a></p>
    <p><a href="/blog/{{ request.user.username }}/article/{{ article_obj.nid }}">>>立即查看</a></p>
    <p><a href="">>>继续编辑</a></p>
    <p><a href="/blog/{{ request.user.username }}/manage">>>后台首页</a></p>
    <p><a href="/">>>博客首页</a></p>

    </div>

{% endblock %}

templates/addArticle.html
{% extends "manage.html" %}

{% block content %}

<div>
<p class="addArt">添加文章</p>
<form action="/blog/addArticle" method="post">
{% csrf_token %}
<div id="edit_title">

    <b>标题</b><span style="color: red">{{ forms.errors.article_title.0 }}</span>
    <br>
    <input name="article_title" type="text" maxlength="200"  id="article_title" value="{{ forms.cleaned_data.article_title }}" style="width:100%;">
</div>
<div id="edit_content">
    <b>内容</b><span style="color: red"></span>
    <br>
    <textarea name="article_content" id="article_content" cols="100" rows="10">{{ forms.cleaned_data.article_content }}</textarea>
</div>
<div class="category">
    <p class="self_cate">>>个人分类</p>
    {% for obj in personal_category %}
        <input type="radio" name="personal_category" value="{{ obj.nid }}">{{ obj.title }}||

    {% endfor %}

    <p class="site_cate">>>网站分类</p>
    {% for obj in SiteCategory %}
    <div>
    <span>{{ obj.name }}:</span>
    {% for article_category in obj.sitearticlecategory_set.all %}
        <input type="radio" name="site_category" value="{{ article_category.id }}">{{ article_category.name }}
    {% endfor %}

    </div>
    {% endfor %}

    <p class="tags">>>选择标签</p>
     <div>
          {% for tag_obj in personal_tag %}
            <input type="checkbox" name="personal_tag" value="{{ tag_obj.nid }}">{{ tag_obj.title }}

        {% endfor %}

     </div>

</div>

<div>
    <input type="submit" class="btn btn-primary" value="发布">
    <a href=""><input type="button" class="btn btn-default" value="取消"></a>
</div>
</form>


</div>

<script charset="utf-8" src="/static/Kindeditor/kindeditor-all.js"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#article_content',{
                    width:"100%",
                    height:"500px",
                    resizeType:1,
                    uploadJson:"/blog/upload",
                    extraFileUploadParams:{
                           csrfmiddlewaretoken:K("[name='csrfmiddlewaretoken']").val(),
                       }

                });
        });
</script>
{% endblock %}

templates/article.html
{% extends "homesite.html" %}

{% block content %}
    <div class="article">
        <a href="/blog/{{ user.username }}/article/{{ article.nid }}"><p class="article_title">{{ article.title }}</p>
        </a>
        <hr>
        <div class="article_content">
            <input id="article_id" type="text" value="{{ article.nid }}" hidden>
            {{ article.articledetail.content|safe }}
        </div>

        <div class="article_caozuo">
            <div class="article_userinfo pull-left">
                <img src="/media/{{ user.avatar }}" width="80px" height="80px">
                <span>{{ user.username }}</span>
            </div>
            <div class="article_userinfo pull-right">
                <div class="pull-right article_bad article_up_down">
                    <div class="one">{{ article.up_count }}</div>
                    <div class="two"><span class="glyphicon glyphicon-thumbs-down up_or_down">反对</span></div>

                </div>
                <div class="pull-right article_good article_up_down">
                    <div class="one">{{ article.up_count }}</div>
                    <div class="two"><span class="glyphicon glyphicon-thumbs-up up_or_down">推荐</span></div>

                </div>
                <div style="padding-left: 30px;height: 30px"></div>
            </div>

        </div>

        <div class="pull-right" style="clear:left;"><p>posted&nbsp;@&nbsp;{{ article.create_time|date:"Y-m-d h:i" }}&nbsp;{{ user.username }}
            &nbsp;阅读({{ article.read_count }})&nbsp;评论({{ article.comment_set.count }})</p></div>
        <div class="comment">
            <span>评论列表(树状)</span>
            <hr>
            <div id="comment_tree_list">


            </div>
            <span>评论列表(楼状)</span>
            <hr>
        </div>
        <div class="commentlist">
            {% for comment in article.comment_set.all %}
                <div class="row">
                    <div class="col-md-10">

                        <p>
                            <a href="#">#{{ forloop.counter }}楼</a><span>{{ comment.create_time|date:"Y-m-d h:i" }}</span>&nbsp;&nbsp;
                            <a href="/blog/{{ comment.user.username }}">{{ comment.user.username }}</a></p>
                        {% if comment.parent_comment_id %}
                        <p>@<a href="/blog/{{ comment.parent_comment.user.username }}">{{ comment.parent_comment.user.username }}</a></p>
                        {% endif %}
                    <p>{{ comment.content }}</p>
                    </div>
                    <div class="col-md-2 function">
                        <input type="text" value="{{ comment.nid }}" hidden>
                        <p class="f1">
                            <a href="#article_comment_content" class="replay_comment" parent_comment_id="{{ comment.nid }}" parent_comment_username="{{ comment.user.username }}">回复</a>
                            <a href="">引用</a>
                        </p>
                        <p class="f2">
                            <a>
                                <span class="comment_func">推荐({{ comment.up_count }})</span>
                            </a>
                            <a>
                                <span class="comment_func">反对({{ comment.down_count }})</span>
                            </a>
                        </p>
                        <p style="margin-left: 30px;">&nbsp;</p>
                    </div>

                </div>
                <hr>
            {% endfor %}
        </div>
        <div>
            <p class="f3 pull-right"><a href="">刷新页面</a><a href="">刷新评论</a><a href="">返回顶部</a></p>
            <p><span class="glyphicon glyphicon-envelope">发表评论</span></p>
            {% if request.user.username %}
                <p><span class="glyphicon glyphicon-user">昵称：</span><input type="text" id="login_user" disabled
                                                                           value="{{ request.user.username }}"></p>
                <p>评论内容：</p>
                {% csrf_token %}
                <p><textarea name="comment_content" id="article_comment_content" cols="50" rows="15"></textarea> </p>
              <p>
                    <button class="btn btn_default" id="sub_comment">提交评论</button>
                    <a href="/logout/">
                        <button class="btn btn_default">退出</button>
                    </a>
                </p>
            {% else %}
                <p><span>你还未登录，请 <a href="/login/">登录</a>发表评论</span></p>
            {% endif %}
        </div>

    </div>

<script charset="utf-8" src="/static/Kindeditor/kindeditor-all.js"></script>
{#<script>#}
{#        KindEditor.ready(function(K) {#}
{#                window.editor = K.create('#article_comment_content',{#}
{##}
{#                    items:[#}
{#                      'image','bold', 'link','indent','plainpaste'#}
{#                    ],#}
{#                    resizeType:1,#}
{#                    uploadJson:"/blog/upload",#}
{#                    extraFileUploadParams:{#}
{#                     csrfmiddlewaretoken:K("[name='csrfmiddlewaretoken']").val(),#}
{#                       },#}
{##}
{##}
{#                });#}
{##}
{#        });#}
{##}
{#</script>#}

<script src="/static/jquery-3.2.1.min.js"></script>
<script>
    //获取评论树
    $.ajax({
        url:'/blog/comment_tree/'+$("#article_id").val()+'',
        success:function (data) {
            var data=JSON.parse(data);
            var s=comment_tree(data) ;
            $("#comment_tree_list").append(s);

        }


    });
    //展开评论树
    function comment_tree(data) {
        var html='';
        $.each(data,function (i,comment_dic){
            username=comment_dic.username;
            user_avatar=comment_dic.user_avatar;
            var comment_str='<div class="coment_tree"><p><a href="">'+username+'</a> <span>'+comment_dic.create_time+'</span></p> <p><img src="/media/'+user_avatar+'" width="50px" height="50px">:'+comment_dic.content+'</p> ';
            if (comment_dic["children_list"]){
                var s=comment_tree(comment_dic["children_list"]);
                comment_str+=s
            }

            comment_str+='</div>';
            html+=comment_str
        });
        return html
    }

</script>
{% endblock %}

templates/category.html
{% extends "manage.html" %}

{% block content %}
<table class="table table-striped">
<thead>
<tr>
    <th>序号</th>
    <th>分类名</th>
    <th>操作</th>
    <th>操作</th>
</tr>
</thead>
<tbody>
{% for category in category_obj %}
    <tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ category.title }}</td>
    <td><button>编辑</button></td>
    <td><button>删除</button></td>
    </tr>

{% endfor %}

</tbody>
</table>
<p style="background-color: #1b6d85;color: white;">添加新分类</p>
<p>分类名：<input type="text"></p>
    <button>Add</button>
{% endblock %}

templates/error404.html
<html>
<head>
    <meta charset="utf-8">
    <title>Error_404_资源不存在</title>
	<style type="text/css">
	body{margin:8% auto 0;max-width: 550px; min-height: 200px;padding:10px;font-family: Verdana,Arial,Helvetica,sans-serif;font-size:14px;}p{color:#555;margin:10px 10px;}img {border:0px;}.d{color:#404040;}
	</style>
</head>
<body>
<a href="/"><img src="/static/images/login.png" ></a>
<p><b>404.</b> 抱歉! 您访问的资源不存在!</p>
<p class="d">请确认您输入的网址是否正确，如果问题持续存在，请发邮件至2532648458@qq.com与我联系。</p>
<p><a href="/">返回网站首页</a></p>
</body>
</html>

templates/homesite.html
{% load mytags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mycss/homesite.css">
</head>
<body>
<div class="container-fluid header">
    <div class="row">
        <div class="col-md-7 header_left">
            <h2>{{ user.username }}</h2>
        </div>
        <div class="col-md-5">
            <div class="pull-left header-btn"><a href="/">博客园</a></div>
            <div class="pull-left header-btn"><a href="/blog/{{ user.username }}">首页</a></div>
            <div class="pull-left header-btn"><a href="/blog/addArticle">写文章</a></div>
            <div class="pull-left header-btn"><a href="">联系</a></div>
            <div class="pull-left header-btn"><a href="">订阅</a></div>
            <div class="pull-left header-btn"><a href="/blog/manage">管理</a></div>
        </div>
    </div>
</div>
{#内容#}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-3 content_left">
            {#            个人基本信息#}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">个人基本信息</h3>
                </div>
                <div class="panel-body">
                    <p class="text-center"><img src="/media/{{ user.avatar }}" width="100" height="100" class="avatar">
                    </p>
                    <p>昵称：<a href="">{{ user.username }}</a></p>
                    <p>园龄：{{ user.create_time|filter_time }}</p>
                </div>
            </div>
            {#            我的标签#}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">我的标签</h3>
                </div>
                <div class="panel-body">
                    {% for tag in user.blog.tag_set.all %}
                        <a href="/blog/{{ user.username }}/tag/{{ tag.title }}">
                            <p>{{ tag.title }}({{ tag.article_set.count }})</p></a>
                    {% endfor %}
                </div>
            </div>
            {#            文章分类#}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">文章分类</h3>
                </div>
                <div class="panel-body">
                    {% for category in user.blog.category_set.all %}
                        <a href="/blog/{{ user.username }}/category/{{ category.title }}">
                            <p>{{ category.title }}({{ category.article_set.count }})</p></a>

                    {% endfor %}

                </div>
            </div>

            {#        时间分类#}
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">时间分类</h3>
                </div>
                <div class="panel-body">
                    {% for date_count in date_name_count %}
                        <a href="/blog/{{ user.username }}/date/{{ date_count.0 }}">
                            <p>{{ date_count.0 }}({{ date_count.1 }})</p></a>

                    {% endfor %}

                </div>
            </div>

        </div>
        <div class="col-md-9 content_right">
            <div class="pull-right"><p>文章-{{ user.article_set.count }} 评论-{{ user.comment_set.count }}</p></div>
            {% block content %}
                {% for article in article_list %}
                    <div class="article">
                        <a href="/blog/{{ user.username }}/article/{{ article.nid }}"><p class="article_title">{{ article.title }}</p></a>
                        <hr>
                        <p>{{ article.desc|safe }}...<a href="/blog/{{ user.username }}/article/{{ article.nid }}">阅读全文</a></p>
                        <div class="pull-right">
                            <p>posted&nbsp;@&nbsp;{{ article.create_time|date:"Y-m-d h:i" }}&nbsp;{{ user.username }}
                                &nbsp;阅读({{ article.read_count }})&nbsp;评论({{ article.comment_set.count }})</p>
                        </div>
                    </div>
                    {% empty %}
                    <p>没有找到任何文章</p>
                {% endfor %}
            {% endblock %}
        </div>
    </div>
</div>

<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/myjs/article.js"></script>



</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>首页</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mycss/index.css">

</head>
<body>
{#导航条#}
<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">博客园</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">新闻</a></li>
                <li><a href="#">博问</a></li>
                <li><a href="#">闪存</a></li>
                <li><a href="#">小组</a></li>
                <li><a href="#">收藏</a></li>
                <li><a href="#">找找看</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="/blog/{{ request.user.username }}"><span class="glyphicon glyphicon-user">{{ request.user.username }}</span></a>
                    </li>
                    <li><a href="/logout/">注销</a></li>
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/register/">注册</a></li>
                {% endif %}

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{#内容部分#}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="content-left">
                <p class="site_classify">网站分类</p>
                {% for obj in site_cate_objs %}
                    <div class="content-left">
                        <p class="classify_name">{{ obj.name }}</p>
                        <div class="article_cate hides">
                            {% for article_cate in obj.sitearticlecategory_set.all %}
                                <a href="/cate/{{ article_cate.name }}"><p>{{ article_cate.name }}({{ article_cate.article_set.count }})</p></a>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6">
            {% for article in article_objs %}
                <div>
                    <a href="/blog/{{ article.user.username }}/article/{{ article.nid }}">{{ article.title }}</a>
                    <div class="row article_content">
                        <div class="col-md-2">
                            <a href="/blog/{{ article.user.username }}"><img src="/media/{{ article.user.avatar }}" alt="" class="article_img"></a>
                        </div>
                        <div class="col-md-10">
                            {{ article.desc|safe }}
                        </div>
                    </div>

                    <a href="/blog/{{ article.user.username }}">{{ article.user.username }}</a><span>发表于{{ article.create_time|date:"Y-m-d" }}</span>
                    <span class="glyphicon glyphicon-thumbs-up article_foot">点赞({{ article.up_count }})</span>
                    <span class="glyphicon glyphicon-comment article_foot">评论({{ article.comment_count }})</span>
                    <span class="glyphicon glyphicon-eye-open article_foot">浏览量({{ article.read_count }})</span>

                    <hr>
                </div>


            {% endfor %}
        </div>
        <div class="col-md-3">
            <div class="content-right">
                <p class="header">我们是谁</p>
                <div class="second_herder">
                    <p>程序员</p>
                    <p>程序员</p>
                    <p>程序员</p>
                    <p>程序员</p>
                </div>
            </div>
            <div class="content-right">
                <p class="header">想说什么</p>
                <div class="second_herder">
                    <p>不修电脑</p>
                    <p>不修电脑</p>
                    <p>不修电脑</p>
                    <p>不修电脑</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/myjs/index.js"></script>
</body>
</html>

templates/tag.html
{% extends "manage.html" %}

{% block content %}

    <table class="table table-striped">
<thead>
<tr>
    <th>序号</th>
    <th>标签名</th>
    <th>操作</th>
    <th>操作</th>
</tr>
</thead>
<tbody>
{% for tag in tags_obj %}
    <tr>
    <td>{{ forloop.counter }}</td>
    <td>{{ tag.title }}</td>
    <td><button>编辑</button></td>
    <td><button>删除</button></td>
    </tr>

{% endfor %}

</tbody>
</table>
    <p style="background-color: #1b6d85;color: white;">添加新标签</p>
    <p>标签名：<input type="text"></p>
    <button>Add</button>

{% endblock %}